server {
    listen 80;
    server_name localhost;
    
    root /var/www/html;

    # Force la redirection vers HTTPS
    location / {
        return 301 https://$host$request_uri;
    }

    # Configuration de phpMyAdmin en HTTPS
    location /phpmyadmin/ {
        proxy_pass http://phpmyadmin:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
